"""empty message

Revision ID: 2bba3ec2ec41
Revises: 3f774de1fcff
Create Date: 2026-03-16 20:22:41.406642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bba3ec2ec41'
down_revision: Union[str, Sequence[str], None] = '3f774de1fcff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_emp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='sexvalue'), nullable=False),
    sa.Column('sal', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='员工的工资'),
    sa.Column('bonus', sa.Integer(), nullable=False, comment='员工的奖金'),
    sa.Column('is_leave', sa.Boolean(), nullable=False, comment='员工是否离职'),
    sa.Column('entry_date', sa.Date(), nullable=False, comment='员工的入职时间'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='记录创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='记录最后一次修改时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_emp')
    # ### end Alembic commands ###
