"""empty message

Revision ID: 3f774de1fcff
Revises: 7607d99ed12b
Create Date: 2026-03-16 19:53:28.074875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f774de1fcff'
down_revision: Union[str, Sequence[str], None] = '7607d99ed12b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_emp', sa.Column('entry_date', sa.Date(), nullable=False, comment='员工的入职时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_emp', 'entry_date')
    # ### end Alembic commands ###
